### Solutions for Web Scraping Homework

In [41]:
# imports
import bs4
from bs4 import BeautifulSoup
import pandas as pd
import requests
import time

In [47]:
# class that holds the individual containers for each restaurant
cont_class = 'container__09f24__sxa9-'

In [48]:
# connect to homework
i = 1
url = f'https://www.yelp.com/search?find_desc=Restaurants&find_loc=London%2C+United+Kingdom&ns=1&start={i}'
req = requests.get(url).text
scraper = BeautifulSoup(req)
restaurants = scraper.find_all('div', {'class':  cont_class})

### Scraping Titles, Categories

In [51]:
#### Getting All Links, Code for Titles and Categories
restaurant_links = [restaurant.find_all('a', {'class': 'css-166la90'}) for restaurant in restaurants]
titles = [link.text for link_group in restaurant_links for link in link_group if 'biz' in link['href']]
titles

['Flat Iron',
 'Restaurant Gordon Ramsay',
 'The Fat Bear',
 'Dishoom',
 'Padella',
 'Ffiona’s Restaurant',
 'The Queens Arms',
 'Abeno',
 'The Golden Chippy',
 'Hawksmoor Seven Dials']

In [52]:
# no list comprehension
titles = []
for link_group in restaurant_links:
    for link in link_group:
        if 'biz' in link['href']:
            titles.append(link.text)

In [54]:
# restaurant categories
cat_links = [restaurant.find_all('p', {'class': 'text__09f24__2NHRu'}) for restaurant in restaurants]
category_one = []
category_two = []
category_three = []
for cat in cat_links:
    for idx in range(3):
        if idx == 0:
            try:
                category_one.append(cat[idx].text)
            except:
                category_one.append(None)
        if idx == 1:
            try:
                category_two.append(cat[idx].text)
            except:
                category_two.append(None)
        if idx == 2:
            try:
                category_three.append(cat[idx].text)
            except:
                category_three.append(None)
total_category_one.extend(category_one)
total_category_two.extend(category_two)
total_category_three.extend(category_three)

In [58]:
# category one
total_category_one

['Fish & Chips',
 'Steakhouses',
 'French',
 'American (Traditional)',
 'Indian',
 'Italian',
 'British',
 'British',
 'Japanese',
 'Fish & Chips',
 'Spanish',
 'British',
 'Mexican',
 'Modern European',
 'Latin American',
 'Coffee & Tea',
 'Korean',
 'British',
 'French',
 'French',
 'Bars',
 'Chinese',
 'Taiwanese',
 'British',
 'Italian',
 'Korean',
 'Middle Eastern',
 'Vietnamese',
 'Pizza',
 'Fish & Chips',
 'Mexican',
 'Bars',
 'Italian',
 'Cafes',
 'Middle Eastern',
 'Pubs',
 'Pubs',
 'Belgian',
 'Italian',
 'Cafes',
 'Italian',
 'Dim Sum',
 'Mediterranean',
 'Korean',
 'British',
 'British',
 'Modern European',
 'Tapas/Small Plates',
 'Italian',
 'Japanese',
 'Persian/Iranian',
 'Ramen',
 'Japanese',
 'Filipino',
 'Italian',
 'Lounges',
 'Indian',
 'Caribbean',
 'Barbeque',
 'Halal',
 'Chinese',
 'Bars',
 'Japanese',
 'Burgers',
 'Japanese',
 'Thai',
 'American (Traditional)',
 'Japanese',
 'British',
 'Seafood',
 'Japanese',
 'Gastropubs',
 'Malaysian',
 'Italian',
 'Malaysian',
 'American (Traditional)',
 'Italian',
 'Cafes',
 'Vietnamese',
 'Japanese',
 'Vietnamese',
 'Italian',
 'Italian',
 'Modern European',
 'Pancakes',
 'Asian Fusion',
 'Cafes',
 'Vietnamese',
 'Italian',
 'British',
 'Brasseries',
 'British',
 'Turkish',
 'Sri Lankan',
 'Peruvian',
 'Thai',
 'Seafood',
 'Pizza',
 'Latin American',
 'Seafood',
 'British',
 'Peruvian',
 'Italian',
 'German',
 'Spanish',
 'Persian/Iranian',
 'Mexican',
 'Steakhouses',
 'Japanese',
 'Latin American',
 'Mexican',
 'Coffee & Tea',
 'British',
 'Latin American',
 'British',
 'Mediterranean',
 'Chicken Shop',
 'Tapas/Small Plates',
 'Pubs',
 'British',
 'Steakhouses',
 'Cafes',
 'Italian',
 'British',
 'Wine Bars',
 'Mexican',
 'Japanese',
 'Pubs',
 'Persian/Iranian',
 'British',
 'Breakfast & Brunch',
 'British',
 'Pubs',
 'Greek',
 'Chicken Shop',
 'Mexican',
 'Bakeries',
 'British',
 'Middle Eastern',
 'Italian',
 'British',
 'Seafood',
 'British',
 'Mexican',
 'British',
 'Indian',
 'Italian',
 'Modern European',
 'Pubs',
 'Indian',
 'Italian',
 'Modern European',
 'Pubs',
 'Spanish',
 'Indian',
 'Portuguese',
 'Argentine',
 'Middle Eastern',
 'Turkish',
 'Gastropubs',
 'Middle Eastern',
 'Ramen',
 'Cocktail Bars',
 'Seafood',
 'Tapas/Small Plates',
 'Portuguese',
 'Peruvian',
 'Sandwiches',
 'British',
 'British',
 'Brasseries',
 'Brasseries',
 'Bars',
 'British',
 'Steakhouses',
 'Gastropubs',
 'British',
 'British',
 'Mediterranean',
 'Spanish',
 'Seafood',
 'Bars',
 'Middle Eastern',
 'Food Court',
 'Spanish',
 'Latin American',
 'British',
 'Japanese',
 'Italian',
 'British',
 'Burgers',
 'Breakfast & Brunch',
 'British',
 'Seafood',
 'Japanese',
 'Gastropubs',
 'Italian',
 'British',
 'British',
 'Modern European',
 'Japanese',
 'Pizza',
 'Seafood',
 'Chinese',
 'Breakfast & Brunch',
 'Japanese',
 'Brasseries',
 'Noodles',
 'British',
 'Japanese',
 'Brasseries',
 'Dim Sum',
 'British',
 'Japanese',
 'Italian',
 'Pizza',
 'Italian',
 'Pubs',
 'British',
 'Japanese',
 'Gastropubs',
 'Dim Sum',
 'Italian',
 'Gastropubs',
 'British',
 'Food Stands',
 'British',
 'Modern European',
 'Thai',
 'Gastropubs',
 'Food Court',
 'British',
 'Modern European',
 'Malaysian',
 'Gastropubs',
 'Vietnamese',
 'Noodles',
 'Arabian',
 'Brasseries',
 'British',
 'Steakhouses',
 'French',
 'American (Traditional)',
 'Indian',
 'Italian',
 'British',
 'British',
 'Japanese',
 'Fish & Chips',
 'British']

In [59]:
# category two
total_category_two

[None,
 None,
 'British',
 'Soul Food',
 None,
 None,
 None,
 'Pubs',
 None,
 None,
 'Tapas Bars',
 'Steakhouses',
 'Bars',
 'Bars',
 'Peruvian',
 'Breakfast & Brunch',
 None,
 'Gastropubs',
 'Modern European',
 None,
 'Venues & Event Spaces',
 'Noodles',
 None,
 None,
 None,
 None,
 'Mediterranean',
 'Noodles',
 'Bars',
 'Seafood',
 None,
 'British',
 None,
 'Korean',
 None,
 'British',
 'British',
 None,
 None,
 None,
 None,
 'Seafood',
 None,
 None,
 'Modern European',
 'Gastropubs',
 None,
 'Spanish',
 None,
 None,
 'Grocery',
 None,
 None,
 None,
 'Coffee & Tea',
 'British',
 'Pakistani',
 None,
 None,
 'Korean',
 None,
 'Waffles',
 None,
 None,
 'Sushi Bars',
 None,
 'Seafood',
 None,
 'Coffee & Tea',
 'Burgers',
 None,
 'British',
 None,
 None,
 None,
 'Burgers',
 None,
 'British',
 None,
 'Barbeque',
 None,
 None,
 None,
 None,
 None,
 'Sushi Bars',
 'British',
 None,
 None,
 'Cocktail Bars',
 'British',
 'Steakhouses',
 None,
 'Asian Fusion',
 'Latin American',
 'Asian Fusion',
 'British',
 None,
 'Wine Bars',
 'British',
 'Bars',
 None,
 None,
 None,
 'Wine Bars',
 None,
 None,
 'Burgers',
 None,
 None,
 None,
 'Sandwiches',
 None,
 None,
 'Pubs',
 'Turkish',
 'American (New)',
 'Wine Bars',
 'Thai',
 None,
 None,
 'Venues & Event Spaces',
 None,
 None,
 'Spanish',
 None,
 'Sushi Bars',
 'Thai',
 None,
 None,
 'Pizza',
 None,
 'British',
 None,
 'Fast Food',
 None,
 'Bistros',
 None,
 'Wine Bars',
 None,
 'Modern European',
 None,
 'French',
 None,
 'Gastropubs',
 None,
 None,
 None,
 'Gastropubs',
 'Asian Fusion',
 None,
 None,
 'Gastropubs',
 'Tapas Bars',
 'Asian Fusion',
 None,
 None,
 'Caterers',
 'Fast Food',
 None,
 None,
 None,
 'British',
 None,
 None,
 None,
 None,
 None,
 'Seafood',
 'Bars',
 'Jazz & Blues',
 None,
 'Russian',
 'Breakfast & Brunch',
 'British',
 None,
 None,
 'Bars',
 'French',
 'Basque',
 None,
 'Russian',
 None,
 None,
 'Basque',
 'Breakfast & Brunch',
 'Bars',
 'Nightlife',
 None,
 None,
 'Sandwiches',
 None,
 'Breakfast & Brunch',
 None,
 'Barbeque',
 'Cocktail Bars',
 None,
 None,
 'Bars',
 'British',
 'Asian Fusion',
 'Italian',
 'Pop-Up Restaurants',
 None,
 None,
 None,
 None,
 'Dim Sum',
 None,
 'Barbeque',
 None,
 None,
 None,
 'Nightlife',
 None,
 None,
 None,
 'Restaurants',
 None,
 None,
 'Cocktail Bars',
 None,
 'Food',
 None,
 None,
 'Italian',
 None,
 None,
 None,
 'British',
 None,
 None,
 None,
 None,
 'British',
 'Noodles',
 None,
 'Middle Eastern',
 None,
 None,
 None,
 'British',
 'Soul Food',
 None,
 None,
 None,
 'Pubs',
 None,
 None,
 'Steakhouses']

In [60]:
# category three
total_category_three

[None,
 None,
 None,
 'Cajun/Creole',
 None,
 None,
 None,
 'Gastropubs',
 None,
 None,
 None,
 'Cocktail Bars',
 None,
 'British',
 'Bars',
 'American (Traditional)',
 None,
 'Venues & Event Spaces',
 'Cocktail Bars',
 None,
 'American (Traditional)',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Noodles',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Cafes',
 None,
 None,
 None,
 None,
 None,
 'Halal',
 None,
 None,
 'Vegan',
 None,
 None,
 None,
 None,
 None,
 None,
 'Burgers',
 None,
 'Tea Rooms',
 None,
 None,
 None,
 None,
 None,
 None,
 'Seafood',
 None,
 'Tea Rooms',
 None,
 'Tapas/Small Plates',
 None,
 None,
 None,
 None,
 None,
 None,
 'Tea Rooms',
 None,
 None,
 'Steakhouses',
 'Coffee & Tea',
 None,
 None,
 None,
 None,
 'Vegetarian',
 None,
 None,
 'Cocktail Bars',
 None,
 None,
 None,
 None,
 None,
 'Tapas Bars',
 None,
 None,
 'British',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Wine Bars',
 'Soul Food',
 'Pizza',
 None,
 None,
 None,
 None,
 None,
 None,
 'Tapas/Small Plates',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Breakfast & Brunch',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Singaporean',
 None,
 None,
 None,
 None,
 'Singaporean',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Breakfast & Brunch',
 None,
 None,
 None,
 None,
 None,
 'Fish & Chips',
 None,
 'Cocktail Bars',
 None,
 'Karaoke',
 'Bars',
 None,
 None,
 None,
 None,
 None,
 'Tapas Bars',
 None,
 'Karaoke',
 None,
 None,
 'Tapas Bars',
 'Sandwiches',
 None,
 'Seafood',
 None,
 None,
 None,
 None,
 'Diners',
 None,
 'Tapas/Small Plates',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Desserts',
 None,
 None,
 None,
 None,
 None,
 None,
 'Tapas/Small Plates',
 None,
 None,
 None,
 'Seafood',
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 'Cocktail Bars',
 None,
 None,
 None,
 None,
 None,
 None,
 'Cajun/Creole',
 None,
 None,
 None,
 'Gastropubs',
 None,
 None,
 'Cocktail Bars']

### Reviews

In [14]:
# paragraphs
restaurant_paragraphs = [restaurant.find_all('p') for restaurant in restaurants]

In [61]:
# get the reviews
reviews = []
for paragraph_group in restaurant_paragraphs:
    if '\xa0more' in paragraph_group[-1].text:
        reviews.append(paragraph_group[-1].text.replace('\xa0more', ''))
    else:
        reviews.append(None)

In [70]:
# our list of reviews
reviews

['“This place is perfect when you want a little bit of everything! \n\nHip with big communal tables, this place definitely draws a young crowd. \n\nEverything we…”',
 '“My husband and I went to this place on our honeymoon -- we specifically sought it out because it was featured on the Food Network and we just HAD to try their…”',
 '“We went there for a few cocktails and all I can say is that we were not disappointed. First of all, this is a great spot, very near to Waterloo station. I…”',
 '“Great restaurant ! Very good Food. I advice you to try their big plates with several dishes. Authentic from country taste ! Very nice service.”',
 '“Scottish Egg and Venison - Delicious Michelin starred pub in Fulham London\n\nI took an Uber on a rainy Friday night through slow London traffic, and it was…”',
 '“It was a Saturday night in London...we were looking for good food, casual atmosphere and we were in the mood for something different.\nMy daughter found this…”',
 '“Cold winter nights call for spicy noodles. BiangBiang can get super crowded on weekends, so stop by on a weeknight.\n\nI highly recommend what I had:\n-Boneless…”',
 "“I'm staying in an AirBnB around the corner from this restaurant, and was a bit skeptical as I walked past it two days prior and was unsure from its exterior…”",
 '“It does not get better than this. Excellent staff.  Smart, kind people.  The perfect spot in primrose hill to eat.  The menu is magnificent. Something amazing…”',
 "“Oh my goodness! I love Scully! We had high expectations knowing the chef's background and because we love NOPI. The flavors were so unique and I loved the…”"]

### Neighborhoods

In [64]:
# get the neighborhoods
neighborhood_spans = [restaurant.find_all('span', {'class': 'css-e81eai'}) for restaurant in restaurants]
neighborhoods = []
for span in neighborhood_spans:
    try:
        if not span[1].text.isdigit():
            neighborhoods.append(span[1].text)
        else:
            neighborhoods.append(None)
    except:
        neighborhoods.append(None)

In [65]:
# list of neighborhoods
neighborhoods

['Soho',
 'Chelsea',
 'Blackfriars',
 'Covent Garden',
 'London Bridge',
 'Kensington',
 'Victoria',
 'Bloomsbury',
 'Deptford',
 'Covent Garden']

### Scraping Price Ranges, Addresses

In [71]:
restaurant_spans = [restaurant.find_all('span') for restaurant in restaurants]

In [72]:
# number of reviews
num_reviews = [int(span_group[4].text) if span_group[4].text.isdigit() else None for span_group in restaurant_spans]

In [73]:
# list of num_reviews
num_reviews

[381, 206, 122, 1850, 208, 266, 120, 102, 110, 344]

In [74]:
# price ranges -- sometimes they have blanks:
price_ranges = []
for span_group in restaurant_spans:
    if '\xA3' in span_group[5].text:
        price_ranges.append(span_group[5].text)
    elif '\xA3' in span_group[6].text:
        price_ranges.append(span_group[6].text)
    else:
        price_ranges.append(None)

In [75]:
# and the price ranges
price_ranges

['££', '££££', '££', '££', '££', '££', '££', '££', '££', '£££']

### Scraping Average Rating

In [76]:
# get all the divs
restaurant_divs = [restaurant.find_all('div', {'role': 'img'}) for restaurant in restaurants]

In [77]:
# pull out the value of the average rating
restaurant_ratings = [float(str(restaurant[0]).split('"')[1].split()[0]) for restaurant in restaurant_divs]

In [78]:
# and we have these values
restaurant_ratings

[4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 5.0, 4.5]

### Final DataFrame

In [79]:
df_dict = {
    'Name': titles,
    'Neighborhood': neighborhoods,
    'PriceRange': price_ranges,
    'AvgRating': restaurant_ratings,
    'NumRatings': num_reviews,
    'CategoryOne': category_one,
    'CategoryTwo': category_two,
    'CategoryThree': category_three,
    'Review': reviews
}

df = pd.DataFrame(df_dict)
df

,Name,Neighborhood,PriceRange,AvgRating,NumRatings,CategoryOne,CategoryTwo,CategoryThree,Review
0,Flat Iron,Food Court,££,4.5,381,Steakhouses,None,None,“This place is perfect when you want a little ...
1,Restaurant Gordon Ramsay,British,££££,4.5,206,French,British,None,“My husband and I went to this place on our ho...
2,The Fat Bear,Modern European,££,4.5,122,American (Traditional),Soul Food,Cajun/Creole,“We went there for a few cocktails and all I c...
3,Dishoom,Malaysian,££,4.5,1850,Indian,None,None,“Great restaurant ! Very good Food. I advice y...
4,Padella,British,££,4.5,208,Italian,None,None,“Scottish Egg and Venison - Delicious Michelin...
5,Ffiona’s Restaurant,Cocktail Bars,££,4.5,266,British,None,None,“It was a Saturday night in London...we were l...
6,The Queens Arms,Noodles,££,4.5,120,British,Pubs,Gastropubs,“Cold winter nights call for spicy noodles. Bi...
7,Abeno,Middle Eastern,££,4.5,102,Japanese,None,None,“I'm staying in an AirBnB around the corner fr...
8,The Golden Chippy,Brasseries,££,5.0,110,Fish & Chips,None,None,“It does not get better than this. Excellent s...
9,Hawksmoor Seven Dials,British,£££,4.5,344,British,Steakhouses,Cocktail Bars,“Oh my goodness! I love Scully! We had high ex...

### Final Answer, That Loops Through The Entire Website

In [43]:
i = 0
num_round = 1
total_titles = []
total_neighborhoods = []
total_price_ranges = []
total_restaurant_ratings = []
total_num_reviews = []
total_category_one = []
total_category_two = []
total_category_three = []
total_reviews = []
looping = True

# helper function to check if a given piece of text is an address or not
def is_address(text):
    text = text.split()
    try:
        # accommodates for values like 34-66, 4/6, etc
        if text[0].replace('-', '').replace('/', '').isdigit() and text[-1].isalpha():
            return True
        else:
            return False
    except:
        return False

while looping:
    cont_class = 'container__09f24__sxa9-'
    url = f'https://www.yelp.com/search?find_desc=Restaurants&find_loc=London%2C+United+Kingdom&ns=1&start={i}'
    req = requests.get(url)
    scraper = BeautifulSoup(req.text)
    restaurants = scraper.find_all('div', {'class': cont_class})
    if len(restaurants) == 0:
        print("No more restaurants found.  Breaking the loop.")
        print(len(restaurants))
        looping = False
        break
    
    #### Getting All Links, Code for Titles and Categories
    restaurant_links = [restaurant.find_all('a', {'class': 'css-166la90'}) for restaurant in restaurants]
    titles = [link.text for link_group in restaurant_links for link in link_group if 'biz' in link['href']]
    total_titles.extend(titles)
    
    # restaurant categories
    cat_links = [restaurant.find_all('p', {'class': 'text__09f24__2NHRu'}) for restaurant in restaurants]
    category_one = []
    category_two = []
    category_three = []
    for cat in cat_links:
        for idx in range(3):
            if idx == 0:
                try:
                    category_one.append(cat[idx].text)
                except:
                    category_one.append(None)
            if idx == 1:
                try:
                    category_two.append(cat[idx].text)
                except:
                    category_two.append(None)
            if idx == 2:
                try:
                    category_three.append(cat[idx].text)
                except:
                    category_three.append(None)
    total_category_one.extend(category_one)
    total_category_two.extend(category_two)
    total_category_three.extend(category_three)
                    
    # getting all the paragraphs within each restaurant
    restaurant_paragraphs = [restaurant.find_all('p') for restaurant in restaurants]
    
    # get the reviews
    reviews = []
    for paragraph_group in restaurant_paragraphs:
        if '\xa0more' in paragraph_group[-1].text:
            reviews.append(paragraph_group[-1].text.replace('\xa0more', ''))
        else:
            reviews.append(None)
                
    total_reviews.extend(reviews)
    
    # get the neighborhoods
    neighborhood_spans = [restaurant.find_all('span', {'class': 'css-e81eai'}) for restaurant in restaurants]
    for span in neighborhood_spans:
        try:
            
            if not span[1].text.isdigit():
                total_neighborhoods.append(span[1].text)
            else:
                total_neighborhoods.append(None)
        except:
            total_neighborhoods.append(None)
    
    # get all the spans in a given page
    restaurant_spans = [restaurant.find_all('span') for restaurant in restaurants]
    
    # get the number of reviews
    num_reviews = [int(span_group[4].text) if span_group[4].text.isdigit() else None for span_group in restaurant_spans]
    total_num_reviews.extend(num_reviews)
    
    # get the price ranges
    price_ranges = []
    for span_group in restaurant_spans:
        if '\xA3' in span_group[5].text:
            price_ranges.append(span_group[5].text)
        elif '\xA3' in span_group[6].text:
            price_ranges.append(span_group[6].text)
        else:
            price_ranges.append(None)
    total_price_ranges.extend(price_ranges)
            
    # get all the rating divs
    restaurant_divs = [restaurant.find_all('div', {'role': 'img'}) for restaurant in restaurants]
    
    # and get the restaurant ratings
    restaurant_ratings = [float(str(restaurant[0]).split('"')[1].split()[0]) for restaurant in restaurant_divs]
    total_restaurant_ratings.extend(restaurant_ratings)
    
    print(f'Finished Round {num_round}, value of i: {i}')
    i += 10
    num_round += 1
    time.sleep(4)
    
df_dict = {
    'Name': total_titles,
    'Neighborhood': total_neighborhoods,
    'PriceRange': total_price_ranges,
    'AvgRating': total_restaurant_ratings,
    'NumRatings': total_num_reviews,
    'CategoryOne': total_category_one,
    'CategoryTwo': total_category_two,
    'CategoryThree': total_category_three,
    'Review': total_reviews
}

df = pd.DataFrame(df_dict)
df

Finished Round 1, value of i: 0
Finished Round 2, value of i: 10
Finished Round 3, value of i: 20
Finished Round 4, value of i: 30
Finished Round 5, value of i: 40
Finished Round 6, value of i: 50
Finished Round 7, value of i: 60
Finished Round 8, value of i: 70
Finished Round 9, value of i: 80
Finished Round 10, value of i: 90
Finished Round 11, value of i: 100
Finished Round 12, value of i: 110
Finished Round 13, value of i: 120
Finished Round 14, value of i: 130
Finished Round 15, value of i: 140
Finished Round 16, value of i: 150
Finished Round 17, value of i: 160
Finished Round 18, value of i: 170
Finished Round 19, value of i: 180
Finished Round 20, value of i: 190
Finished Round 21, value of i: 200
Finished Round 22, value of i: 210
Finished Round 23, value of i: 220
Finished Round 24, value of i: 230
No more restaurants found.  Breaking the loop.
0

,Name,Neighborhood,PriceRange,AvgRating,NumRatings,CategoryOne,CategoryTwo,CategoryThree,Review
0,The Mayfair Chippy,Mayfair,££,4.5,283.0,Fish & Chips,None,None,“A chippy befitting of it's neighborhood.\n\nC...
1,Flat Iron,Soho,££,4.5,381.0,Steakhouses,None,None,“I really hate to say OMG because I'm really t...
2,Restaurant Gordon Ramsay,Chelsea,££££,4.5,206.0,French,British,None,"“This wasn't the best meal that I've had, but ..."
3,The Fat Bear,Blackfriars,££,4.5,122.0,American (Traditional),Soul Food,Cajun/Creole,"“WOW, this place is delicious!\n\nOur family s..."
4,Dishoom,Covent Garden,££,4.5,1850.0,Indian,None,None,“Amazing Bombay food with an Irani twist. All ...
...,...,...,...,...,...,...,...,...,...
235,The Little Viet Kitchen,Islington,££,4.0,45.0,Vietnamese,Noodles,Cocktail Bars,“It was a Saturday night in London...we were l...
236,Xi’An BiangBiang Noodles,Petticoat Lane,None,4.0,18.0,Noodles,None,None,“Cold winter nights call for spicy noodles. Bi...
237,Ali Baba,Marylebone,£,4.5,12.0,Arabian,Middle Eastern,None,“I'm staying in an AirBnB around the corner fr...
238,Greenberry Café,Chalk Farm,££,4.0,33.0,Brasseries,None,None,“It does not get better than this. Excellent s...
239,Scully,Leicester Square,None,5.0,13.0,British,None,None,“Oh my goodness! I love Scully! We had high ex...