In [74]:
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor
import category_encoders as ce
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline

In [3]:
df = pd.read_csv('../data/master.csv', parse_dates = ['visit_date'])

In [4]:
df.drop('calendar_date', axis=1, inplace=True)

In [5]:
df = df.fillna(0)

In [6]:
df.head()

,id,visit_date,visitors,day_of_week,holiday,genre,area,latitude,longitude,reserve_visitors
0,air_ba937bf13d40fb24,2016-01-13,25,Wednesday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,0.0
1,air_ba937bf13d40fb24,2016-01-14,32,Thursday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,0.0
2,air_ba937bf13d40fb24,2016-01-15,29,Friday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,0.0
3,air_ba937bf13d40fb24,2016-01-16,22,Saturday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,0.0
4,air_ba937bf13d40fb24,2016-01-18,6,Monday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,0.0

In [9]:
te  = ce.TargetEncoder(cols=['id', 'area'])
ore = ce.OrdinalEncoder()
mod = GradientBoostingRegressor(verbose=1, random_state=42)

pipe = make_pipeline(te, ore, mod)

In [10]:
df.sort_values(by=['id', 'visit_date'], inplace=True)

In [18]:
df.groupby('id').mean()

,visitors,holiday,latitude,longitude,reserve_visitors
id,,,,,
air_00a91d42b08b08d9,26.081897,0.004310,35.694003,139.753595,7.379310
air_0164b9927d20bcc3,9.248322,0.033557,35.658068,139.751599,10.872483
air_0241aa3964b7f861,9.896465,0.042929,35.712607,139.779996,6.078283
air_0328696196e46f18,7.939655,0.051724,34.701279,135.528090,8.646552
air_034a3d5b40d5b1b1,14.828685,0.059761,34.692337,135.472229,8.494024
...,...,...,...,...,...
air_fea5dc9594450608,14.485401,0.036496,34.710896,137.725940,8.664234
air_fee8dcf4d619598e,26.027778,0.059028,34.695124,135.197853,8.739583
air_fef9ccb3ba0da2f7,9.620408,0.061224,34.815149,134.685353,9.061224
air_ffcc2d5087e1b476,20.242798,0.020576,35.658068,139.751599,7.893004
air_fff68b929994bfbd,5.089219,0.044610,35.708146,139.666288,9.100372

In [14]:
unique_ids = df['id'].unique().tolist()

In [ ]:
for rest in unique_ids:
    temp_data = df[df['id'] == rest]
    test_data = temp_data.iloc[-15:]

In [17]:
df[df['id'] == unique_ids[0]].iloc[-15:]

,id,visit_date,visitors,day_of_week,holiday,genre,area,latitude,longitude,reserve_visitors
167048,air_00a91d42b08b08d9,2017-04-05,35,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,2.0
167049,air_00a91d42b08b08d9,2017-04-06,29,Thursday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,8.0
167050,air_00a91d42b08b08d9,2017-04-07,17,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,1.0
167051,air_00a91d42b08b08d9,2017-04-08,9,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,33.0
167052,air_00a91d42b08b08d9,2017-04-10,17,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0
167053,air_00a91d42b08b08d9,2017-04-11,43,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,2.0
167054,air_00a91d42b08b08d9,2017-04-12,28,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,2.0
167055,air_00a91d42b08b08d9,2017-04-13,34,Thursday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,7.0
167056,air_00a91d42b08b08d9,2017-04-14,39,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,4.0
167057,air_00a91d42b08b08d9,2017-04-17,19,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0
167058,air_00a91d42b08b08d9,2017-04-18,35,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0
167059,air_00a91d42b08b08d9,2017-04-19,17,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0
167060,air_00a91d42b08b08d9,2017-04-20,38,Thursday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,1.0
167061,air_00a91d42b08b08d9,2017-04-21,55,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,6.0
167062,air_00a91d42b08b08d9,2017-04-22,18,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,37.0

In [19]:
test = df.groupby('id').apply(lambda x: x.iloc[-15:])
train = df.groupby('id').apply(lambda x: x.iloc[:-15])

In [23]:
train.reset_index(drop=True, inplace=True)

In [24]:
val = train.groupby('id').apply(lambda x: x.iloc[-15:])
train = train.groupby('id').apply(lambda x: x.iloc[:-15])

In [25]:
# define some functions that we can reuse
def create_val_splits(df, val_units=15, return_val=False):
    """Function that will take in a dataset and split it up into training, validation, and test sets"""
    # split into training, validation, and test sets
    df = df.drop('visit_date', axis=1)
    train = df.groupby('id').apply(lambda x: x.iloc[:-val_units]).reset_index(drop=True)
    test  = df.groupby('id').apply(lambda x: x.iloc[-val_units:]).reset_index(drop=True)
    
    if return_val:
        val   = train.groupby('id').apply(lambda x: x.iloc[-val_units:]).reset_index(drop=True)
        train = train.groupby('id').apply(lambda x: x.iloc[:-val_units]).reset_index(drop=True)
        return train, val, test
    else:
        return train, test

In [26]:
train, val, test = create_val_splits(df, return_val=True)

In [27]:
X_train, y_train = train.drop('visitors', axis=1), train['visitors']
X_val, y_val = val.drop('visitors', axis=1), val['visitors']

In [28]:
pipe.fit(X_train, y_train)

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.5358           51.64s
         2         236.4692           42.76s
         3         222.2922           40.12s
         4         210.6249           36.67s
         5         201.0720           37.66s
         6         193.0328           37.88s
         7         186.5980           41.15s
         8         181.1435           43.72s
         9         176.7334           42.86s
        10         173.0381           42.58s
        20         155.6810           31.25s
        30         151.2830           25.76s
        40         149.5396           21.54s
        50         148.3023           17.81s
        60         147.1310           14.60s
        70         146.5496           10.89s
        80         145.9973            7.21s
        90         145.6742            3.64s
       100         145.2671            0.00s

Pipeline(steps=[('targetencoder', TargetEncoder(cols=['id', 'area'])),
                ('ordinalencoder',
                 OrdinalEncoder(cols=['day_of_week', 'genre'],
                                mapping=[{'col': 'day_of_week',
                                          'data_type': dtype('O'),
                                          'mapping': Friday       1
Saturday     2
Monday       3
Tuesday      4
Wednesday    5
Thursday     6
Sunday       7
NaN         -2
dtype: int64},
                                         {'col': 'genre',
                                          'data_type': dtype('O'),
                                          'mapping': Italian/French                   1
Izakaya                          2
Dining bar                       3
Cafe/Sweets                      4
Japanese food                    5
Western food                     6
Okonomiyaki/Monja/Teppanyaki     7
Other                            8
Yakiniku/Korean food             9
Asian                           10
Bar/Cocktail                    11
Creative cuisine                12
International cuisine           13
Karaoke/Party                   14
NaN                             -2
dtype: int64}])),
                ('gradientboostingregressor',
                 GradientBoostingRegressor(verbose=1))])

In [33]:
pipe[-1].estimators_

array([[DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)],
       [DecisionTreeRegressor(criterion='friedman_mse', max_depth=3,
                              random_state=RandomState(MT19937) at 0x27B24E19240)]],
      dtype=object)

In [34]:
pipe.predict(X_val)

array([33.9144731 , 33.44882017, 21.87924511, ...,  4.90443237,
        5.12950757,  4.51168977])

In [32]:
pipe.score(X_val, y_val)

0.4934377820532636

In [36]:
df['year'] = df['visit_date'].dt.year
df['month'] = df['visit_date'].dt.month
df['day'] = df['visit_date'].dt.day
df['quarter'] = df['visit_date'].dt.quarter
df['time'] = (df['visit_date'] - df['visit_date'].min()).dt.days

In [37]:
train, val, test = create_val_splits(df, return_val=True)

In [38]:
X_train, y_train = train.drop('visitors', axis=1), train['visitors']
X_val, y_val = val.drop('visitors', axis=1), val['visitors']

In [39]:
pipe.fit(X_train, y_train)
pipe.score(X_val, y_val)

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.5358            1.06m
         2         236.4692            1.08m
         3         222.2922            1.05m
         4         210.6249            1.26m
         5         201.0720            1.20m
         6         193.0328            1.13m
         7         186.5980            1.08m
         8         181.1435            1.02m
         9         176.7334           59.41s
        10         173.0381           57.44s
        20         155.6810           45.73s
        30         151.0803           38.76s
        40         148.7138           33.61s
        50         147.2701           28.36s
        60         146.0362           22.97s
        70         145.0940           17.25s
        80         144.1010           11.17s
        90         143.5775            5.23s
       100         143.0504            0.00s

0.5010683305325951

In [41]:
pipe[-1].set_params(n_estimators=200, random_state=42)

GradientBoostingRegressor(n_estimators=200, verbose=1)

In [42]:
pipe.fit(X_train, y_train)

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.5358            3.12m
         2         236.4692            2.75m
         3         222.2922            2.57m
         4         210.6249            2.34m
         5         201.0720            2.21m
         6         193.0328            2.13m
         7         186.5980            2.06m
         8         181.1435            2.15m
         9         176.7334            2.20m
        10         173.0381            2.19m
        20         155.6810            1.88m
        30         151.0803            1.74m
        40         148.7138            1.63m
        50         147.2701            1.65m
        60         146.0362            1.50m
        70         145.0940            1.37m
        80         144.1010            1.27m
        90         143.5775            1.15m
       100         143.0504            1.03m
       200         140.4717            0.00s

Pipeline(steps=[('targetencoder', TargetEncoder(cols=['id', 'area'])),
                ('ordinalencoder',
                 OrdinalEncoder(cols=['day_of_week', 'genre'],
                                mapping=[{'col': 'day_of_week',
                                          'data_type': dtype('O'),
                                          'mapping': Friday       1
Saturday     2
Monday       3
Tuesday      4
Wednesday    5
Thursday     6
Sunday       7
NaN         -2
dtype: int64},
                                         {'col': 'genre',
                                          'data_type': dtype('O'),
                                          'mapping': Italian/French                   1
Izakaya                          2
Dining bar                       3
Cafe/Sweets                      4
Japanese food                    5
Western food                     6
Okonomiyaki/Monja/Teppanyaki     7
Other                            8
Yakiniku/Korean food             9
Asian                           10
Bar/Cocktail                    11
Creative cuisine                12
International cuisine           13
Karaoke/Party                   14
NaN                             -2
dtype: int64}])),
                ('gradientboostingregressor',
                 GradientBoostingRegressor(n_estimators=200, verbose=1))])

In [43]:
pipe.score(X_val, y_val)

0.5062701774490461

In [ ]:
df

In [56]:
df

,id,visit_date,visitors,day_of_week,holiday,genre,area,latitude,longitude,reserve_visitors,year,month,day,quarter,time,yesterday,last_week,seven_day_ma
166836,air_00a91d42b08b08d9,2016-07-01,35,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0,2016,7,1,3,182,NaN,NaN,NaN
166837,air_00a91d42b08b08d9,2016-07-02,9,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,4.0,2016,7,2,3,183,35.0,NaN,NaN
166838,air_00a91d42b08b08d9,2016-07-04,20,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0,2016,7,4,3,185,9.0,NaN,NaN
166839,air_00a91d42b08b08d9,2016-07-05,25,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0,2016,7,5,3,186,20.0,NaN,NaN
166840,air_00a91d42b08b08d9,2016-07-06,29,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,0.0,2016,7,6,3,187,25.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216643,air_fff68b929994bfbd,2017-04-18,6,Tuesday,0,Bar/Cocktail,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,0.0,2017,4,18,2,473,3.0,1.0,4.285714
216644,air_fff68b929994bfbd,2017-04-19,2,Wednesday,0,Bar/Cocktail,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,0.0,2017,4,19,2,474,6.0,6.0,5.000000
216645,air_fff68b929994bfbd,2017-04-20,2,Thursday,0,Bar/Cocktail,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,1.0,2017,4,20,2,475,2.0,1.0,4.428571
216646,air_fff68b929994bfbd,2017-04-21,4,Friday,0,Bar/Cocktail,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,6.0,2017,4,21,2,476,2.0,5.0,4.571429
216647,air_fff68b929994bfbd,2017-04-22,5,Saturday,0,Bar/Cocktail,Tōkyō-to Nakano-ku Nakano,35.708146,139.666288,37.0,2017,4,22,2,477,4.0,7.0,4.428571

In [46]:
df['yesterday'] = df.groupby('id')['visitors'].shift(1)
df['last_week'] = df.groupby('id')['visitors'].shift(7)
df['seven_day_ma'] = df.groupby('id')['visitors'].rolling(7).mean().shift().values

In [57]:
df = df.bfill()

In [58]:
train, val, test = create_val_splits(df, return_val=True)

In [59]:
X_train, y_train = train.drop('visitors', axis=1), train['visitors']
X_val, y_val = val.drop('visitors', axis=1), val['visitors']

In [60]:
pipe.fit(X_train, y_train)
pipe.score(X_val, y_val)

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.1927            3.21m
         2         235.4788            2.68m
         3         220.7651            2.79m
         4         208.6898            2.81m
         5         198.6838            2.79m
         6         190.1258            2.69m
         7         183.0460            2.61m
         8         177.2780            2.57m
         9         172.4111            2.52m
        10         168.0901            2.47m
        20         148.1283            2.42m
        30         142.4784            2.32m
        40         140.1507            2.20m
        50         138.8598            2.14m
        60         137.5969            1.93m
        70         136.6072            1.82m
        80         135.8504            1.70m
        90         135.2389            1.55m
       100         134.8387            1.39m
       200         131.3272            0.00s

0.5301585762539989

In [61]:
df['visitors'].rolling(3).mean()

166836          NaN
166837          NaN
166838    21.333333
166839    18.000000
166840    24.666667
            ...
216643     5.333333
216644     3.666667
216645     3.333333
216646     2.666667
216647     3.666667
Name: visitors, Length: 252108, dtype: float64

In [64]:
pipe[0].set_params(min_samples_leaf=30)

TargetEncoder(cols=['id', 'area'], min_samples_leaf=30)

In [63]:
pipe

Pipeline(steps=[('targetencoder', TargetEncoder(cols=['id', 'area'])),
                ('ordinalencoder',
                 OrdinalEncoder(cols=['day_of_week', 'genre'],
                                mapping=[{'col': 'day_of_week',
                                          'data_type': dtype('O'),
                                          'mapping': Friday       1
Saturday     2
Monday       3
Tuesday      4
Wednesday    5
Thursday     6
Sunday       7
NaN         -2
dtype: int64},
                                         {'col': 'genre',
                                          'data_type': dtype('O'),
                                          'mapping': Italian/French                   1
Izakaya                          2
Dining bar                       3
Cafe/Sweets                      4
Japanese food                    5
Western food                     6
Okonomiyaki/Monja/Teppanyaki     7
Other                            8
Yakiniku/Korean food             9
Asian                           10
Bar/Cocktail                    11
Creative cuisine                12
International cuisine           13
Karaoke/Party                   14
NaN                             -2
dtype: int64}])),
                ('gradientboostingregressor',
                 GradientBoostingRegressor(n_estimators=200, verbose=1))])

In [65]:
max_features = [0.8, 0.7, 0.6]

for feature in max_features:
    pipe[-1].set_params(max_features=feature)
    pipe.fit(X_train, y_train)
    print(feature, pipe.score(X_train, y_train), pipe.score(X_val, y_val))

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.2790            4.25m
         2         235.7303            3.42m
         3         221.2777            3.10m
         4         209.0714            2.85m
         5         199.0752            2.61m
         6         190.9031            2.46m
         7         183.9122            2.32m
         8         177.8418            2.26m
         9         172.9905            2.19m
        10         168.6818            2.38m
        20         148.9407            2.01m
        30         143.0723            1.89m
        40         140.5265            1.74m
        50         138.8900            1.58m
        60         137.7653            1.44m
        70         137.0741            1.26m
        80         136.3727            1.08m
        90         135.8722           55.52s
       100         135.3158           48.00s
       200         131.8592            0.00s
0.8 0.5195567767007083 0.5410779629197668

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.2304           48.48s
         2         235.7521           46.37s
         3         221.2319           49.34s
         4         209.1401           48.96s
         5         199.1754           48.31s
         6         190.8790           47.36s
         7         183.8803           47.22s
         8         177.9689           46.84s
         9         172.8616           46.51s
        10         168.7436           46.11s
        20         148.9042           42.82s
        30         143.3566           41.98s
        40         140.7729           38.76s
        50         139.1948           36.03s
        60         138.1933           33.75s
        70         137.3727           31.25s
        80         136.8460           28.83s
        90         136.1825           26.42s
       100         135.5197           24.24s
       200         131.9139            0.00s
0.7 0.5193572955557675 0.500155196473636

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         254.6847            1.60m
         2         236.9235            1.49m
         3         222.2179            1.42m
         4         210.1132            1.41m
         5         199.9663            1.44m
         6         191.6474            1.59m
         7         184.6126            1.95m
         8         178.5471            1.91m
         9         173.2673            1.97m
        10         169.0458            2.04m
        20         149.0816            1.89m
        30         143.4218            1.69m
        40         140.7820            1.60m
        50         138.9377            1.59m
        60         137.8966            1.44m
        70         137.1768            1.30m
        80         136.6050            1.16m
        90         136.0277            1.03m
       100         135.3980           55.84s
       200         132.0600            0.00s
0.6 0.5188250675982451 0.5283557749906191

In [66]:
pipe[-1].set_params(max_features=0.8)

GradientBoostingRegressor(max_features=0.8, n_estimators=200, verbose=1)

In [67]:
estimators = [150, 200]
tree_depth = [3, 4]
cv_scores  = []

for estimator in estimators:
    for depth in tree_depth:
        pipe[-1].set_params(n_estimators=estimator, max_depth=depth)
        print(f"Fitting for {estimator}, {depth}")
        pipe.fit(X_train, y_train)
        cv_scores.append((pipe.score(X_val, y_val), estimator, depth))

Fitting for 150, 3

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.2068            1.48m
         2         235.7614            1.34m
         3         221.1342            1.37m
         4         209.0765            1.55m
         5         198.9366            1.51m
         6         190.4833            1.46m
         7         183.5563            1.43m
         8         177.7673            1.44m
         9         172.8295            1.48m
        10         168.8237            1.47m
        20         148.8278            1.29m
        30         143.2740            1.17m
        40         140.7896            1.09m
        50         139.1581           58.18s
        60         138.1457           56.40s
        70         137.1681           50.56s
        80         136.3664           43.64s
        90         135.8311           37.34s
       100         135.3289           31.01s
Fitting for 150, 4

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         251.9690            1.94m
         2         233.4478            1.92m
         3         217.9999            1.82m
         4         205.3350            1.79m
         5         194.8803            1.74m
         6         186.1881            1.69m
         7         179.0571            1.69m
         8         173.0295            1.67m
         9         168.0886            1.66m
        10         163.7843            1.64m
        20         144.6015            1.63m
        30         139.1599            1.77m
        40         136.8125            1.60m
        50         135.1226            1.48m
        60         133.4860            1.30m
        70         132.5475            1.15m
        80         131.5041            1.03m
        90         130.8912           53.83s
       100         130.4087           45.26s
Fitting for 200, 3

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         253.3726            2.21m
         2         235.9120            2.31m
         3         221.5530            2.19m
         4         209.5737            2.09m
         5         199.2688            2.04m
         6         190.7191            1.99m
         7         183.7675            1.93m
         8         177.9380            1.90m
         9         173.0191            1.88m
        10         168.8175            1.86m
        20         149.0415            1.70m
        30         143.3315            1.65m
        40         140.4962            1.67m
        50         139.1853            1.60m
        60         137.9891            1.54m
        70         137.0824            1.42m
        80         136.4121            1.30m
        90         135.8384            1.17m
       100         135.3414            1.09m
       200         131.4848            0.00s
Fitting for 200, 4

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         251.8089            2.45m
         2         233.1131            2.39m
         3         217.8229            2.67m
         4         205.2155            2.63m
         5         194.8763            2.74m
         6         186.2157            2.78m
         7         178.8600            2.77m
         8         172.8367            2.68m
         9         167.8685            2.60m
        10         163.5222            2.57m
        20         144.7051            2.26m
        30         139.6226            2.33m
        40         137.2206            2.28m
        50         134.8978            2.14m
        60         133.2013            1.97m
        70         132.2672            1.87m
        80         131.3523            1.60m
        90         130.7872            1.47m
       100         130.1202            1.33m
       200         125.8471            0.00s

In [68]:
cv_scores

[(0.533580148931056, 150, 3),
 (0.5321401235240178, 150, 4),
 (0.5115827487576112, 200, 3),
 (0.5367662402422206, 200, 4)]

In [69]:
pipe[-1].set_params(n_estimators=200, max_depth=4)

GradientBoostingRegressor(max_depth=4, max_features=0.8, n_estimators=200,
                          verbose=1)

In [70]:
X_train = pd.concat([X_train, X_val])
y_train = pd.concat([y_train, y_val])

In [71]:
pipe.fit(X_train, y_train)

C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):
C:\Users\Jonat\anaconda3\lib\site-packages\category_encoders\utils.py:21: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
  elif pd.api.types.is_categorical(cols):

      Iter       Train Loss   Remaining Time
         1         254.4987            3.07m
         2         235.6266            3.36m
         3         219.8434            3.06m
         4         206.9012            2.98m
         5         196.2125            2.95m
         6         187.5177            2.91m
         7         180.2622            2.90m
         8         174.0002            2.86m
         9         168.9815            2.83m
        10         164.7952            2.77m
        20         145.5022            2.74m
        30         140.2163            2.49m
        40         137.8384            2.35m
        50         135.9545            2.16m
        60         134.2865            2.06m
        70         133.5073            1.90m
        80         132.4435            1.75m
        90         131.9714            1.61m
       100         131.1769            1.46m
       200         126.7443            0.00s

Pipeline(steps=[('targetencoder',
                 TargetEncoder(cols=['id', 'area'], min_samples_leaf=30)),
                ('ordinalencoder',
                 OrdinalEncoder(cols=['day_of_week', 'genre'],
                                mapping=[{'col': 'day_of_week',
                                          'data_type': dtype('O'),
                                          'mapping': Friday       1
Saturday     2
Monday       3
Tuesday      4
Wednesday    5
Thursday     6
Sunday       7
NaN         -2
dtype: int64},
                                         {'col': 'genre',
                                          'data_type': dtype('O'),
                                          'mapping': Italian/French                   1
Izakaya                          2
Dining bar                       3
Cafe/Sweets                      4
Japanese food                    5
Western food                     6
Okonomiyaki/Monja/Teppanyaki     7
Other                            8
Yakiniku/Korean food             9
Asian                           10
Bar/Cocktail                    11
Creative cuisine                12
International cuisine           13
Karaoke/Party                   14
NaN                             -2
dtype: int64}])),
                ('gradientboostingregressor',
                 GradientBoostingRegressor(max_depth=4, max_features=0.8,
                                           n_estimators=200, verbose=1))])

In [73]:
X_test, y_test = test.drop('visitors', axis=1), test['visitors']
pipe.score(X_test, y_test)

0.5157716835784234